### PR TITLE
build: add missing randomness checks

### PR DESCRIPTION
**Pull request by div72**

### CODE REVIEW

**Review by jamescowens — APPROVED** [review]
utACK. This is marked still in progress, but looks good to me.

**Comment by div72** [comment]
@wilkart What version of FreeBSD are you using?

**Comment by wilkart** [comment]
@div72 My recent approach was on FreeBSD 14.0 but I use many FreeBSD releases so I can easily verify the build on all supported if we need.
https://www.freebsd.org/security/#sup

**Comment by div72** [comment]
@wilkart I got `use of undeclared identifier: 'be32enc'` with 14.1 on this PR, can you try that?

**Comment by wilkart** [comment]
Dear @div72, it seems on FreeBSD 14.1 the change I pass below (reverting to original) allows building. I suggest we revert my solution. I will check in future release of 13.4-RELEASE.
In next step I will update document how to build on FreeBSD 14.1 and higher releases.

```
[gridcoin@amarara ~/Gridcoin-Research]$ git diff
diff --git a/src/pbkdf2.cpp b/src/pbkdf2.cpp
index bcd75f3f8..588b50e7d 100644
--- a/src/pbkdf2.cpp
+++ b/src/pbkdf2.cpp
@@ -16,7 +16,6 @@ be32dec(const void *pp)
 }
 */

-#ifndef __FreeBSD__
 static inline void
 be32enc(void *pp, uint32_t x)
 {
@@ -27,7 +26,6 @@ be32enc(void *pp, uint32_t x)
     p[1] = (x >> 16) & 0xff;
     p[0] = (x >> 24) & 0xff;
 }
-#endif

 /**
  * PBKDF2_SHA256(passwd, passwdlen, salt, saltlen, c, buf, dkLen):
```

**Comment by wilkart** [comment]
@div72 
I confirm I have successfully built on both FreeBSD 13.3-RELEASE and FreeBSD 14.1-RELEASE after your refactoring to use WriteBE32.

**Review by jamescowens — APPROVED** [review]
ACK
