### ISSUE TITLE
gridcoin 5.0.0.0 will not build with boost-1.74

### ISSUE THREAD

**Issue by kingbeowulf** [gridcoin-community/Gridcoin-Research#1879]
The latest stable boost is v. 1.74
Slackware64-current (15.0 13-Sep-2020)
**Error message:** 
```
backup.cpp: In function ‘bool BackupConfigFile(const string&)’:
backup.cpp:52:75: error: ‘boost::filesystem::copy_option’ has not been declared
   52 |             filesystem::copy_file(ConfigSource, ConfigTarget, filesystem::copy_option::overwrite_if_exists);
      |                                                                           ^~~~~~~~~~~
backup.cpp: In function ‘bool BackupWallet(const CWallet&, const string&)’:
backup.cpp:91:75: error: ‘boost::filesystem::copy_option’ has not been declared
   91 |             filesystem::copy_file(WalletSource, WalletTarget, filesystem::copy_option::overwrite_if_exists);
      |  
```

**Patch to fix error to allow build:**
```
diff -Naur Gridcoin-Research-5.0.0.0-orig/src/backup.cpp Gridcoin-Research-5.0.0.0/src/backup.cpp
--- Gridcoin-Research-5.0.0.0-orig/src/backup.cpp	2020-09-03 19:18:07.000000000 -0700
+++ Gridcoin-Research-5.0.0.0/src/backup.cpp	2020-09-13 13:52:33.254715832 -0700
@@ -49,7 +49,7 @@
     try
     {
         #if BOOST_VERSION >= 104000
-            filesystem::copy_file(ConfigSource, ConfigTarget, filesystem::copy_option::overwrite_if_exists);
+            filesystem::copy_file(ConfigSource, ConfigTarget, filesystem::copy_options::overwrite_existing);
         #else
             filesystem::copy_file(ConfigSource, ConfigTarget);
         #endif
@@ -88,7 +88,7 @@
         try
         {
 #if BOOST_VERSION >= 104000
-            filesystem::copy_file(WalletSource, WalletTarget, filesystem::copy_option::overwrite_if_exists);
+            filesystem::copy_file(WalletSource, WalletTarget, filesystem::copy_options::overwrite_existing);
 #else
             filesystem::copy_file(WalletSource, WalletTarget);
 #endif
```

**Comments:**
It seems backward compatibility upstream with the boost-1.7x series is not guaranteed.

**Comment by jamescowens** [comment]
Please use the hotfix branch. This should be fixed there.

**Comment by jamescowens** [comment]
In particular, see the commit https://github.com/gridcoin-community/Gridcoin-Research/commit/22ab1a9a60cec9fb8a0c1c61864cb9050f026261 which has already been merged on the hotfix branch.

**Comment by kingbeowulf** [comment]
As the saying goes..."a day late and a dollar short."  Thanks.

**Comment by kingbeowulf** [comment]
fixed in commit 22ab1a9 hotfix branch
