### ISSUE TITLE
Unable to compile on OS X 10.10.5

### ISSUE THREAD

**Issue by Geesu** [gridcoin-community/Gridcoin-Research#46]
I was following the guide on: https://gridcoin.us/Guides/gridcoin-install.htm  It compiled quite a bit then unfortunately failed due to `ld: symbol(s) not found for architecture x86_64`. I'm not sure how to proceed.

https://gist.github.com/Geesu/0a99266515944cca3c1e

The only differences were the versions of libraries, specifically:
- openssl 1.0.2d_1
- miniupnpc 1.9.20150609
- boost 1.58.0

**Comment by aripoya** [comment]
I got same Issue

**Comment by Git-Jiro** [comment]
Hi!
I also had some issues compiling Gridcoin for OS X.
I made the effort to create a homebrew recipe for it.

These are the steps to use my homebrew recipe:
1. Go to http://brew.sh and install Homebrew for OS X
2. Install my brew tap: brew tap Git-Jiro/jiro
3. Install Gridcoin via: brew install gridcoin
4. Happy brewing / Happy Gridcoin "mining"

Regards,
Jiro

**Comment by Geesu** [comment]
Yea I ended up using that but it doesn't compile the daemon :/

**Comment by Git-Jiro** [comment]
Hi @Geesu,
it does compile the daemon, but you have to ask for it. ;-)
Try this: brew reinstall gridcoin --with-cli

Regards,
Jiro

**Comment by Geesu** [comment]
Awesome thanks :)  Do you have a branch out there that fixes the compilation issues btw? I tried one branch on your github repo but it failed with a different error.

**Comment by Git-Jiro** [comment]
Your welcome!

The recipe compiles directly from the gridcoin/Gridcoin-Research repo.
It has an embedded patch that fixes some compilation issues.
On the other hand the recipe uses a slightly reconfigured version of openssl, because gridcoin does not link with the default configuration of openssl shipped by homebrew.

**Comment by aripoya** [comment]
please  add "brew install --HEAD git-jiro/jiro/gridcoin" after "brew tap Git-Jiro/jiro" i got this ariwibowo@MacBookAir:~% brew install gridcoin
Error: git-jiro/jiro/gridcoin is a head-only formula
Install with `brew install --HEAD git-jiro/jiro/gridcoin`

btw thanks for your recipes

**Comment by ArtTucker** [comment]
After running `brew install --HEAD git-jiro/jiro/gridcoin`, several minutes into the process, I do get one particular error:

> ==> Downloading https://homebrew.bintray.com/bottles-jiro/nossl-qt-4.8.7_1.el_capitan.bottle.tar.gz
> curl: (22) The requested URL returned error: 404 Not Found
> Error: Failed to download resource "nossl-qt"
> Download failed: https://homebrew.bintray.com/bottles-jiro/nossl-qt-4.8.7_1.el_capitan.bottle.tar.gz
> Warning: Bottle installation failed: building from source.

Thanks for the brew. I was having similar troubles with an OSX installation.

**Comment by Git-Jiro** [comment]
@ArtTucker that looks like an error in my brew recipe for my special version of QT.
Brew should not try to fetch a bottle for my version, since there is none.
I already commited a fix to my repo.

Try this:
brew update
brew install --HEAD git-jiro/jiro/gridcoin

BR Martin

**Comment by gridcoin** [comment]
Hi guys, has this been resolved, can we close now?

Thanks.

**Comment by Git-Jiro** [comment]
@gridcoin Yes, I think this can be closed now ...

**Comment by ghost** [comment]
@Git-Jiro I just installed via homebrew. Installation finished without errors, but when I launch the app, it crashes on the splash screen, no error message provided, only the classic 'ignore', 'restart' dialog from macOS.

What could be the problem here?

EDIT: Issue seems to be of the actual gridcoin 3.5.9.9 version and not the mac port. 
https://steemit.com/gridcoin/@dutch/gridcoin-wallet-v3-5-9-9-clean-install-crash-fix-inside
Hope it will be fixed in the main version soon; @gridcoin keep us posted.

**Comment by iFoggz** [comment]
it has been applied to be released in next release. for now create ur gridcoinresearch.conf file yourself in the mean time and you shouldnt have any issues :) fix is #491

**Comment by Git-Jiro** [comment]
Looks like this issue is already taken care of. :)
