### ISSUE TITLE
cannot build on MacOS 11.6.4

### ISSUE THREAD

**Issue by Git-Jiro** [gridcoin-community/Gridcoin-Research#2457]
# Bug Report

**Current behavior**

Unable to build GridCoin 5.3.3.0 from my cask

**Expected behavior**

Build GridCoin 5.3.3.0 without issues.

**Steps to reproduce:**

brew install git-jiro/jiro/gridcoin -d

**Screenshots**

**Gridcoin version**

url "https://github.com/gridcoin-community/Gridcoin-Research/archive/5.3.3.0.tar.gz"
sha256 "45c80a24a289c5488df8cf3fdc713b19679a9a248de75227b552d72321ac0ed7"

**Machine specs**
- OS: macOS Big Sur 11.6.4
- CPU: 2,5 GHz Quad-Core Intel Core i7
- RAM: 16 GB 1600 MHz DDR3
- Disk size: 500 GB
- Disk Type (HD/SSD): SSD

**Extra information**

Dump of end of Brew output:
==> Patching
==> cd src ; ../contrib/nomacro.pl
==> ./autogen.sh
==> ./configure
==> make NO_UPGRADE=1 USE_UPNP=1 USE_QRCODE=1
Last 15 lines from /Users/martin/Library/Logs/Homebrew/gridcoin/04.make:
  CXX      gridcoin/libgridcoin_util_a-tally.o
  CXX      gridcoin/libgridcoin_util_a-tx_message.o
  CXX      gridcoin/libgridcoin_util_a-upgrade.o
  CXX      libgridcoin_util_a-init.o
  CXX      libgridcoin_util_a-key.o
  CXX      libgridcoin_util_a-keystore.o
key.cpp:144:9: error: invalid argument type 'void' to unary expression
    if (!BN_zero(zero)) { ret=-1; goto err; }
        ^~~~~~~~~~~~~~
  CXX      libgridcoin_util_a-logging.o
1 error generated.
make[2]: *** [libgridcoin_util_a-key.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
/usr/local/Homebrew/Library/Homebrew/shims/shared/git --version
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --version
/usr/local/Homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
BuildError: Failed executing: make NO_UPGRADE=1 USE_UPNP=1 USE_QRCODE=1

**Comment by div72** [comment]
@Git-Jiro Do you have `openssl@1.1`?

**Comment by Git-Jiro** [comment]
Yup, using openssl@1.1 fixed it.
Thanks!
