### ISSUE TITLE
Asio SSL compile error

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1163]
```
rpcserver.cpp: In function ‘void StartRPCThreads()’:
rpcserver.cpp:608:77: error: no matching function for call to ‘boost::asio::ssl::context::context(boost::asio::io_service&, boost::asio::ssl::context_base::method)’
/usr/include/boost/asio/ssl/impl/context.ipp:326:1: note: candidate: ‘boost::asio::ssl::context::context(boost::asio::ssl::context&&)’
/usr/include/boost/asio/ssl/impl/context.ipp:63:1: note: candidate: ‘boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)’
```

It looks like the new boost version does not need io_service in the call to ccl context.
Boost: 1.67.0-4

This same error was troubling me on several open source projects.

**Comment by tomasbrod** [comment]
Introduced in #1139 at [line of commit](https://github.com/gridcoin-community/Gridcoin-Research/commit/24e39560313a4b8f81c0504ce947deae8abcc209#diff-c10c2955226a46a341b05d00f59525b1R1020) @denravonska

**Comment by denravonska** [comment]
Fixed (again), thanks.

Edit: I don't have boost-1.67 installed so let me know if there are more issues.

**Comment by tomasbrod** [comment]
Arch Linux master race :smirk:
