### PR TITLE
Latest Berkeley DB (v6+) compatibility fix

### PR DESCRIPTION
**Pull request by xPh03n1x**
The current version of the db.cpp fails when compiled with libdb 6:

```
db.cpp: In member function ‘void CDBEnv::EnvShutdown()’:
db.cpp:42:16: error: call of overloaded ‘DbEnv(int)’ is ambiguous
         DbEnv(0).remove(strPath.c_str(), 0);
```

### CODE REVIEW

File: src/db.cpp [hunk 1]
```diff
@@ -39,7 +39,7 @@ void CDBEnv::EnvShutdown()
     if (ret != 0)
         printf("EnvShutdown exception: %s (%d)\n", DbEnv::strerror(ret), ret);
     if (!fMockDb)
-        DbEnv(0).remove(strPath.c_str(), 0);
+        DbEnv((u_int32_t)0).remove(strPath.c_str(),0);
```
Comment (denravonska) [inline src/db.cpp]: It should be `uint32_t`, right?

Comment (xPh03n1x) [reply src/db.cpp]: The u_ prefix I believe serves across different platforms. It definitely worked on a RHEL 6.6 x86_64

**Comment by tomasbrod** [comment]
Why use Berkeley DB when we have Level-DB, that is a step back?

Btw: I am interested in adding Tokyo or Kyoto Cabinet support as I like that kv-store impl.

File: src/db.cpp (hunk 1 above)
Comment (tomasbrod) [reply src/db.cpp]: that space was actually good there, but it works so whatever xD

**Review by tomasbrod — APPROVED** [review]

File: src/db.cpp (hunk 1 above)
Comment (denravonska) [reply src/db.cpp]: Agree on the space, and drop the stray underscore so we get to a standard `uint32_t` :)

**Comment by tomasbrod** [comment]
Why use Berkeley DB when we have Level-DB, that is a step back?

**Comment by ghost** [comment]
Isn't Berkeley DB already in the code since the beginning?

**Comment by tomasbrod** [comment]
Yes, it is as I found hard when compiling for windows. And apparently it is used for wallet file to stay compatible. If wallet is opened using new BDB, it will not be recognized by old version.

**Review by tomasbrod — APPROVED** [review]
